name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Publish the project
      run: dotnet publish --configuration Release --output ./output --no-restore

    - name: Deploy to production
      run: |
        echo "Deploying to production server"
        # Adicione aqui os comandos de deploy específicos, por exemplo:
        # scp -r ./output user@productionserver:/path/to/deploy
        # ssh user@productionserver 'dotnet /path/to/deploy/yourapp.dll'
      env:
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}